=== MalCiech/Projects/XML/Lab4/kamil/1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="karta_pojazdu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="data_utworzenia">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="miejcowosc"/>
              <xs:element type="xs:date" name="data"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="dane_samochodu">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nr_katalogowy"/>
              <xs:element type="xs:string" name="marka"/>
              <xs:element type="xs:string" name="model"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="dane_uztkownika">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="identyfikator"/>
              <xs:element type="xs:string" name="imie"/>
              <xs:element type="xs:string" name="nazwiko"/>
              <xs:element type="xs:string" name="stanowisko"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lista_wyjazdow">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pozycja" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:integer" name="przebieg_km"/>
                    <xs:element type="xs:string" name="miejsce_wyjazdu"/>
                    <xs:element type="xs:string" name="cel_podrozy"/>
                  </xs:sequence>
                  <xs:attribute type="xs:integer" name="nr" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="data_uzytkowania">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pobrania_auta">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:date" name="dzien"/>
                    <xs:element type="xs:time" name="godzina"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="zdania_auta">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:date" name="dzien"/>
                    <xs:element type="xs:time" name="godzina"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="samochod_wydal">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="imie"/>
              <xs:element type="xs:string" name="nazwisko"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="samochod_odebral">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="imie"/>
              <xs:element type="xs:string" name="nazwisko"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MalCiech/Projects/XML/Lab4/kamil/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Kamil Janikowski 16597 -->

<karta_pojazdu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1.xsd">
    <data_utworzenia>
        <miejcowosc>Warszawa</miejcowosc>
        <data>2016-03-10</data>
    </data_utworzenia>
    <dane_samochodu>
        <nr_katalogowy>PG2044</nr_katalogowy>
        <marka>Opel</marka>
        <model>Vectra</model>
    </dane_samochodu>
    <dane_uztkownika>
        <identyfikator>PG2014/I</identyfikator>
        <imie>Karol</imie>
        <nazwiko>Kraszewki</nazwiko>
        <stanowisko>Specjalista - działu informatyki</stanowisko>
    </dane_uztkownika>
    <lista_wyjazdow>
        <pozycja nr="1">
            <przebieg_km>50</przebieg_km>
            <miejsce_wyjazdu>Warszawa - Stegny (Centrala)</miejsce_wyjazdu>
            <cel_podrozy>Usunięcie awarii sieci</cel_podrozy>
        </pozycja>
        <pozycja nr="2">
            <przebieg_km>100</przebieg_km>
            <miejsce_wyjazdu>Grodzisk Maz. (Oddział terenowy)</miejsce_wyjazdu>
            <cel_podrozy>Konserwacja serwera</cel_podrozy>
        </pozycja>
        <pozycja nr="3">
            <przebieg_km>80</przebieg_km>
            <miejsce_wyjazdu>Warszawa - Bielany (Oddział terenowy)</miejsce_wyjazdu>
            <cel_podrozy>Instalacja oprogramowania</cel_podrozy>
        </pozycja>
    </lista_wyjazdow>
    <data_uzytkowania>
        <pobrania_auta>
            <dzien>2014-03-08</dzien>
            <godzina>09:30:00</godzina>
        </pobrania_auta>
        <zdania_auta>
            <dzien>2014-03-08</dzien>
            <godzina>18:20:00</godzina>
        </zdania_auta>
    </data_uzytkowania>
    <samochod_wydal>
        <imie>Andrzej</imie>
        <nazwisko>Stefaniak</nazwisko>
    </samochod_wydal>
    <samochod_odebral>
        <imie>Hubert</imie>
        <nazwisko>Kamionek</nazwisko>
    </samochod_odebral>
</karta_pojazdu>
