=== MalCiech/Projects/XML/Lab4/kamil/2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dokumenty_agencja">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="umowa">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="numer"/>
              <xs:element type="xs:string" name="miejscowosc"/>
              <xs:element type="xs:date" name="data_utworzenia"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="dane_stron_umowy">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="agencja">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="nazwa"/>
                    <xs:element name="adres">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="miasto"/>
                          <xs:element type="xs:string" name="kod_pocztowy"/>
                          <xs:element type="xs:string" name="ulica"/>
                          <xs:element type="xs:integer" name="numer"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="NIP"/>
                    <xs:element type="xs:integer" name="REGON"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="poszukujacy">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="imie"/>
                    <xs:element type="xs:string" name="nazwisko"/>
                    <xs:element name="adres">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="miasto"/>
                          <xs:element type="xs:string" name="kod_pocztowy"/>
                          <xs:element type="xs:string" name="ulica"/>
                          <xs:element type="xs:string" name="numer"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:integer" name="PESEL"/>
                    <xs:element type="xs:string" name="dowod"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="czas_obowiazywania">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="czas_od"/>
              <xs:element type="xs:date" name="czas_do"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lista_nieruchomosci">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="pozycja" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nieruchomosc">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="typ"/>
                          <xs:element type="xs:integer" name="powierzchnia"/>
                          <xs:element type="xs:integer" name="dzialka"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="adres">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="miejscowosc"/>
                          <xs:element type="xs:string" name="ulica"/>
                          <xs:element type="xs:integer" name="numer"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:integer" name="nr" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="prowizja">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="procent"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="agent_prowadzacy">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="imie"/>
              <xs:element type="xs:string" name="nazwisko"/>
              <xs:element type="xs:integer" name="telefon"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MalCiech/Projects/XML/Lab4/kamil/2.xml
<?xml version="1.0" encoding="UTF-8"?>
 <dokumenty_agencja xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="2.xsd">
    <umowa>
        <numer>5676</numer>
        <miejscowosc>Warszawa</miejscowosc>
        <data_utworzenia>2014-10-01</data_utworzenia>
    </umowa>
    <dane_stron_umowy>
        <agencja>
            <nazwa>Stoleczne Centrum Nierchomosci</nazwa>
            <adres>
                <miasto>Warszawa</miasto>
                <kod_pocztowy>01-042</kod_pocztowy>
                <ulica>ul.Okopowa</ulica>
                <numer>56</numer>
            </adres>
            <NIP>723-230-21-03</NIP>
            <REGON>567382911</REGON>
        </agencja>
        <poszukujacy>
            <imie>Miroslaw</imie>
            <nazwisko>Strzalinski</nazwisko>
            <adres>
                <miasto>Radzymin</miasto>
                <kod_pocztowy>05-250</kod_pocztowy>
                <ulica>ul.Kościelna</ulica>
                <numer>12/4</numer>
            </adres>
            <PESEL>71091456340</PESEL>
            <dowod>DD 678844</dowod>
        </poszukujacy>
    </dane_stron_umowy>

    <czas_obowiazywania>
        <czas_od>2014-10-01></czas_od>
        <czas_do>2014-12-31</czas_do>
    </czas_obowiazywania>
    <lista_nieruchomosci>
        <pozycja nr="1">
            <nieruchomosc>
                <typ>Dom wolnostojacy</typ>
                <powierzchnia>240</powierzchnia>
                <dzialka>1000</dzialka>
            </nieruchomosc>
            <adres>
                <miejscowosc>Podkowa Lesna</miejscowosc>
                <ulica>Kwiatowa</ulica>
                <numer>23</numer>
            </adres>
        </pozycja>
        <pozycja nr="2">
            <nieruchomosc>
                <typ>Segment</typ>
                <powierzchnia>200</powierzchnia>
                <dzialka>560</dzialka>
            </nieruchomosc>
            <adres>
                <miejscowosc>Milanówek</miejscowosc>
                <ulica>Spokojna</ulica>
                <numer>7</numer>
            </adres>
        </pozycja>
        <pozycja nr="3">
            <nieruchomosc>
                <typ>Dom wolnostojacy</typ>
                <powierzchnia>260</powierzchnia>
                <dzialka>3500</dzialka>
            </nieruchomosc>
            <adres>
                <miejscowosc>Brwinów</miejscowosc>
                <ulica>Cicha</ulica>
                <numer>12</numer>
            </adres>
        </pozycja>
    </lista_nieruchomosci>
    <prowizja>
        <procent>3</procent>
    </prowizja>
    <agent_prowadzacy>
        <imie>Agnieszka</imie>
        <nazwisko>Kownacka</nazwisko>
        <telefon>227552476</telefon>
    </agent_prowadzacy>
</dokumenty_agencja>
