=== MalCiech/Projects/XML/Lab4/Praca_domowa/agencja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dokument_agencji">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="umowa">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:integer" name="numer"/> 
                    <xs:element name="zawarcie_umowy">
                     <xs:complexType>
                        <xs:sequence>
                           <xs:element type="xs:string" name="miejscowosc"/>
                           <xs:element type="xs:date" name="data"/> 
                        </xs:sequence>
                     </xs:complexType>
                    </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="tabela">
              <xs:complexType>
                <xs:sequence>
                    <xs:element name="agencja">
                       <xs:complexType>
                         <xs:sequence>
                          <xs:element type="xs:string" name="nazwa_agencji"/>
                           <xs:element name="adres">
                               <xs:complexType>
                                   <xs:sequence>
                                       <xs:element type="xs:string" name="miejscowosc"/>
                                       <xs:element type="xs:string" name="ulica"/>
                                       <xs:element type="xs:string" name="kod"/>
                                       <xs:element type="xs:integer" name="nr_domu"/> 
                                   </xs:sequence>
                               </xs:complexType>
                           </xs:element>
                           <xs:element type="xs:string" name="nip"/>
                           <xs:element type="xs:integer" name="regon"/>
                         </xs:sequence>
                       </xs:complexType>
                    </xs:element>
                    <xs:element name="poszukujacy">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="dane_osobowe">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element type="xs:string" name="imie"/>
                                            <xs:element type="xs:string" name="nazwisko"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="adres">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element type="xs:string" name="miejscowosc"/>
                                            <xs:element type="xs:string" name="ulica"/>
                                            <xs:element type="xs:string" name="kod"/>
                                            <xs:element type="xs:integer" name="nr_domu"/>
                                            <xs:element type="xs:integer" name="nr_lokalu"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element type="xs:string" name="pesel"/>
                                <xs:element name="dowod">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element type="xs:string" name="seria"/>
                                            <xs:element type="xs:integer" name="nr_serii"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>             
            <xs:element name="termin_umowy">
                <xs:complexType>
                   <xs:sequence>
                    <xs:element type="xs:date" name="termin_zawarcia"/>
                    <xs:element type="xs:date" name="termin_zakonczenia"/>   
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:string" name="zobowiazanie"/>      
            <xs:element name="tabela">
                <xs:complexType>
                     <xs:sequence>
                        <xs:element name="lp" maxOccurs="unbounded" minOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nieruchomosc">    
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element type="xs:string" name="typ"/>
                                                <xs:element type="xs:integer" name="powierzchnia"/>
                                                <xs:element type="xs:integer" name="dzialka"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                        <xs:element name="adres">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element type="xs:string" name="miejscowosc"/>
                                    <xs:element type="xs:string" name="ulica"/>
                                    <xs:element type="xs:integer" name="numer"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                                </xs:sequence>
                        <xs:attribute type="xs:integer" name="nr" use="optional"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
        </xs:element>
        <xs:element name="prowizja">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="procent"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="oswiadczenie"/> 
        <xs:element name="agent_prowadzacy">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="imie"/>
              <xs:element type="xs:string" name="nazwisko"/>
              <xs:element type="xs:integer" name="telefon"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="podpis">
          <xs:complexType>
            <xs:sequence>
                <xs:element name="agencja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="imie"/>
                            <xs:element type="xs:string" name="nazwisko"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="kupujacy">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="imie"/>
                            <xs:element type="xs:string" name="nazwisko"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MalCiech/Projects/XML/Lab4/Praca_domowa/lab4_zadanie1_agencja.xml
<?xml version="1.0" encoding="UTF-8"?>

 <dokument_agencji xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="agencja.xsd">
    <umowa>
        <numer> 5676 </numer>
        <zawarcie_umowy>
            <miejscowosc> Warszawa </miejscowosc>
            <data>2014-10-01</data>       
        </zawarcie_umowy>  
    </umowa>
    <tabela>
        <agencja>                 
            <nazwa_agencji> Stołeczne Centrum Nieruchomości</nazwa_agencji>
            <adres>
                <miejscowosc> Warszawa </miejscowosc>
                <ulica>Ul. Okopowa </ulica>
                <kod>01-042</kod>
                <nr_domu>56</nr_domu>
            </adres>
            <nip>723-230-21-03</nip>
            <regon> 567382911</regon>
        </agencja>
        <poszukujacy>
             <dane_osobowe>
                     <imie> Mirosław </imie>
                     <nazwisko> Strzaliński</nazwisko>
             </dane_osobowe>
             <adres>
                <miejscowosc> Radzymin </miejscowosc>
                <ulica> ul. Kościelna </ulica>
                <kod>05-250</kod>
                <nr_domu>12</nr_domu>
                <nr_lokalu>4</nr_lokalu>
            </adres>
            <pesel>71091456340</pesel>
            <dowod>
                <seria>DD</seria>
                <nr_serii>678844</nr_serii>  
            </dowod>       
       </poszukujacy>
    </tabela>
    <termin_umowy>
       <termin_zawarcia>2014-10-01 </termin_zawarcia>
       <termin_zakonczenia>2014-12-31 </termin_zakonczenia>   
    </termin_umowy>
    <zobowiazanie>Poszukujący zobowiązuje się iż ewentualnego zakupu którejś z poniższych nieruchomości dokona za pośrednictwem agencji SCN.</zobowiazanie>
    <tabela>
        <lp nr="1">
            <nieruchomosc>
                <typ>Dom wolnostojacy</typ>
                <powierzchnia>240</powierzchnia>
                <dzialka>1000</dzialka>
            </nieruchomosc>
            <adres>
                <miejscowosc>Podkowa Lesna</miejscowosc>
                <ulica>Kwiatowa</ulica>
                <numer>23</numer>
            </adres>
        </lp>
        <lp nr="2">
            <nieruchomosc>
                <typ>Segment</typ>
                <powierzchnia>200</powierzchnia>
                <dzialka>560</dzialka>
            </nieruchomosc>
            <adres>
                <miejscowosc>Milanówek</miejscowosc>
                <ulica>Spokojna</ulica>
                <numer>7</numer>
            </adres>
        </lp>
        <lp nr="3">
            <nieruchomosc>
                <typ>Dom wolnostojacy</typ>
                <powierzchnia>260</powierzchnia>
                <dzialka>3500</dzialka>
            </nieruchomosc>
            <adres>
                <miejscowosc>Brwinów</miejscowosc>
                <ulica>Cicha</ulica>
                <numer>12</numer>
            </adres>
        </lp>
    </tabela>
    <prowizja>
        <procent>3</procent>
    </prowizja>
    <oswiadczenie>Poszukujący oświadcza jednocześnie iż jeżeli dokona transakcji dotyczącej którejś z powyższych nieruchomości z pominięciem agencji SCN, wypłaci agencji należne wynagrodzenie z tytułu prowizji.</oswiadczenie>
    <agent_prowadzacy>
        <imie>Agnieszka</imie>
        <nazwisko>Kownacka</nazwisko>
        <telefon>227552476</telefon>
   </agent_prowadzacy>
    <podpis>
        <agencja>
            <imie>Agnieszka</imie>
            <nazwisko>Kownacka</nazwisko> 
        </agencja>
        <kupujacy>
            <imie>Mirosław</imie>
            <nazwisko>Strzaliński</nazwisko> 
        </kupujacy>
    </podpis>

</dokument_agencji>
